name: Build

on:
  push:
    branches: [ 'main' ]

jobs:
  build-ubuntu-macos:
    name: Build on ${{ matrix.os }} (${{ matrix.cc }} compiler)
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        cc: [ gcc, clang ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.18.x'

      - name: Install clang
        if: matrix.cc == 'clang'
        uses: KyleMayes/install-llvm-action@v1.5.0
        with:
          version: '13'

      - name: Install apt packages
        if: matrix.os == 'ubuntu-latest' && matrix.cc == 'gcc'
        run: |
          sudo apt-get update
          sudo apt-get install -y -q gcc

      - name: Install brew packages
        if: matrix.os == 'macos-latest' && matrix.cc == 'gcc'
        run: |
          brew update --quiet
          brew install gcc

      # - env:
      #     CC: ${{ matrix.cc }}
      #   run: |
      #     echo "os: $RUNNER_OS -- compiler: $CC"
      #     echo "compiler version: $($CC --version)"
      #     echo "cmake version: $(cmake --version)"
      - name: Build
        env:
          CC: ${{ matrix.cc }}
        run: ${{ github.workspace }}/ci/build.sh

  build-windows:
    name: Build on ${{ matrix.os }} (${{ matrix.config }} config)
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        config: [ MSVC, MINGW ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.18.x'

      - name: Setup Microsoft Visual Studio Compiler
        if: matrix.config == 'MSVC'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        env:
          CONFIG: ${{ matrix.config }}
        run: powershell ${{ github.workspace }}\ci\build-windows.ps1
