# TODO run after ubuntu-latest build
# use artifacts to pass the build/ dir between the workflows

name: clang-tidy check

on:
  workflow_run:
    workflows: [ 'Build' ]
    branches: [ 'main' ]
    types:
      - completed

jobs:
  clang-tidy-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download cmake build artifact
        uses: actions/download-artifact@v2

      - name: Run clang-tidy
        run:
          "${{ github.workspace }}/.github/scripts/run-clang-tidy.sh"
