# TODO run after ubuntu-latest build
# use artifacts to pass the build/ dir between the workflows

name: clang-tidy check

on:
  workflow_run:
    workflows: [ 'Build' ]
    types:
      - completed

jobs:
  clang-tidy-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        cc: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Display before
        run: ls -R

      - name: Download cmake build artifact
        # since the default github action for artifacts doesn't allow
        # cross-workflow artifact downloads, we need to use this workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          # keep in sync with the build workflow filename
          workflow: build.yml
          name: ${{ matrix.os }}-${{ matrix.cc }}-cmake-build

      - name: Display after
        run: ls -R

      # TODO check that clang-tidy is installed
      # run clang-tidy for multiple OS'es (?)
      # check that this workflow runs ONLY IF BUILD SUCCEEDED
      - name: Run clang-tidy
        run: ${{ github.workspace }}/.github/scripts/run-clang-tidy.sh
