# TODO run after ubuntu-latest build
# use artifacts to pass the build/ dir between the workflows

name: clang-tidy check

on:
  workflow_run:
    workflows: [ 'Build' ]
    types:
      - completed

jobs:
  clang-tidy-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        cc: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download cmake build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.cc }}-cmake-build

      # TODO check that clang-tidy is installed
      # run clang-tidy for multiple OS'es (?)
      # check that this workflow runs ONLY IF BUILD SUCCEEDED
      - name: Run clang-tidy
        run: ${{ github.workspace }}/.github/scripts/run-clang-tidy.sh"
