name: echo environ

on: pull_request

jobs:
  echo-environ:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "repo ${{ github.repository }}; pr ${{ github.event.pull_request.number }}; branch ${{ github.event.pull_request.head.sha }}"
